server:
  port: 8092
  servlet:
    context-path: /irrigation-system

spring:
  datasource:
    url: jdbc:h2:~/recruitment
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-ui
  main:
    allow-bean-definition-overriding: true
app:
  name: irrigation-system
  version: 1
  description: Recruitment task for Andela's client

rabbitmq:
  queue:
    email:
      name: notification
  exchange:
    name: irrigation_exchange
  routing:
    email:
      key: email_routing_key

camunda:
  bpm:
    default-serialization-format: application/json
    authorization:
      enabled: false
    filter:
      create: All
    history-level: activity
    id-generator: strong
    database:
      schema-update: true
      type: h2
    webapp:
      index-redirect-enabled: false
    admin-user:
      id: demo
      password: demo
    login:
      enabled: true
      user-id: admin
#resilience4j:
#  retry:
#    instances:
#      flightSearch:
#        max-attempts: 5
#        waitDuration: 3s
