create table plot
(
    id         bigint generated by default as identity,
    crop_name  varchar(255),
    crop_type  varchar(255),
    location   varchar(255),
    owner_name varchar(255),
    size       bigint,
    primary key (id)
) insert into plot (id, crop_name, crop_type, location, owner_name, size) values (default, ?, ?, ?, ?, ?);

select *
from plot;