create table plot
(
    id             bigint generated by default as identity,
    crop_name      varchar(255),
    crop_type      varchar(255),
    location       varchar(255),
    owner_name     varchar(255),
    size_in_meters bigint,
    primary key (id)
)

insert into plot (id, crop_name, crop_type, location, owner_name, size_in_meters)
values (default, 'banana', 'prenial', 'lagos', 'brume', 1000);

select *
from plot;