create table sensor
(
    id               bigint generated by default as identity,
    plot_id          bigint,
    sensor_number    varchar(255),
    sensors_endpoint varchar(255),
    primary key (id)
);
alter table sensor
    add constraint UKp5v1g2suaknewq1ljksefcl4r unique (plot_id, sensor_number);

insert into sensor (id, plot_id, sensor_number, sensors_endpoint)
values (default, 1, 'QUGJ192901', 'http://localhost:8092/irrigation-system/rest/sensor/trigger');