create table time_slots
(
    id                 bigint generated by default as identity,
    cubic_water_amount double,
    day                integer not null,
    frequency          integer,
    sensor_number      varchar(255),
    status             integer,
    time_value         integer not null,
    primary key (id)
)

