create table time_slots
(
    id                 bigint generated by default as identity,
    cubic_water_amount double,
    day_value          integer not null,
    frequency          varchar(255),
    sensor_number      varchar(255),
    status             varchar(255),
    time_value         integer not null,
    primary key (id)
);
create table configure_plot
(
    plot_id      bigint,
    time_slot_id bigint not null,
    primary key (time_slot_id)
);
alter table configure_plot
    add constraint FKqcuxmq2heq1g6gevjl1b963xe foreign key (plot_id) references plot;
alter table configure_plot
    add constraint FKiu3o2pgt7w6j65m27bofx52fo foreign key (time_slot_id) references time_slots;

-- cron expression to run every 2 minutes
insert into time_slots(cubic_water_amount, day_value, frequency, sensor_number, status, time_value)
values (1000, 0, 'MINUTE', 'klasjh2', 'PENDING', 2;

-- cron expression to run every  thursday by 2 pm
insert into time_slots(cubic_water_amount, day_value, frequency, sensor_number, status, time_value)
values (1000, 4, 'HOURLY', 'klasjh2', 'PENDING', 14;